### ISSUE TITLE
create build

### ISSUE THREAD

**Issue by slimslenderslacks** [atomisthq/automation-client-clj#7]
- let's deploy this to clojars but at com.atomist/automation-client-clj instead
- we should use our gpg signing keys
- let's use the atomist clojars user from 1password (instead of whostolebenfrog because so that we ahve the creds in 1password)
- kipz thinks he can get this all running as long as we build with boot (gpg problems otherwise).

**Comment by whostolebenfrog** [comment]
All sounds good except:

> let's use the atomist clojars user from 1password (instead of whostolebenfrog because so that we ahve the creds in 1password)

There is no need to share a user - we can use the 1password user to add all our individual clojars accounts to that group. Less of a pain than dragging a shared user from 1password. If we always publish under com.atomist then we only have to do it once.

**Comment by kipz** [comment]
This is going to be for CI, so using the atomist account makes sense here.

**Comment by kipz** [comment]
We have a basic build. No signing yet.
